#! /bin/sh
# autostart apps
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh
picom -b
feh --randomize --bg-fill ~/.config/backgrounds/* &
xrdb merge ~/.Xresources &

## Configuraciones -------------------------------#
~/.config/polybar/launch.sh &

# workspaces 
bspc monitor -d 1 2 3 4 5

bspc config focus_follows_pointer true

bspc config top_padding 20

# borders
bspc config focused_border_color "#353b45"
bspc config normal_border_color "#282c34"
bspc config border_width 2
bspc config borderless_monocle true

#gaps 
bspc config gapless_monocle false
bspc config window_gap 15
bspc config split_ratio 0.50

#apps
bspc rule -a Gnome-terminal follow=on focus=on state=floating
bspc rule -a Google-chrome desktop='^2' follow=on focus=on
bspc rule -a firefox desktop='^2' follow=on focus=on
bspc rule -a Org.gnome.Nautilus desktop='^3' follow=on focus=on
bspc rule -a Gedit desktop='^3' follow=on focus=on
